apiVersion: apps/v1
kind: Deployment
metadata:
  name: okmi2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okmi2
  template:
    metadata:
      labels:
        app: okmi2
    spec:
      containers:
      - image: okteto.dev/okmi2:latest
        name: okmi2
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: ParameterSSENCYPT
          value: "chacha20-ietf-poly1305"
        - name: Vless_UUID
          value: "1fd9e34f-29c9-4b40-ab13-e2b8427ec708"
        - name: Vless_Path
          value: "/1fd9e34f-29c9-4b40-ab13-e2b8427ec708-vless"
        - name: Vmess_UUID
          value: "1fd9e34f-29c9-4b40-ab13-e2b8427ec708"
        - name: Vmess_Path
          value: "/1fd9e34f-29c9-4b40-ab13-e2b8427ec708-vmess"
        - name: Trojan_UUID
          value: "1fd9e34f-29c9-4b40-ab13-e2b8427ec708"
        - name: Trojan_Path
          value: "/1fd9e34f-29c9-4b40-ab13-e2b8427ec708-trojan"
        - name: SS_UUID
          value: "1fd9e34f-29c9-4b40-ab13-e2b8427ec708"
        - name: SS_Path
          value: "/1fd9e34f-29c9-4b40-ab13-e2b8427ec708-ss"
        - name: Share_Path
          value: "/1fd9e34f-29c9-4b40-ab13-e2b8427ec708-share"
